name: Log Webhook Timestamp
on:
  workflow_dispatch:
  repository_dispatch:
    types: [webhook-received]

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.HUBSPOT_PAT }}  # Use your PAT here
      
      - name: Log Timestamp
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo "Webhook received at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> webhook-timestamps.txt
          git add webhook-timestamps.txt
          git commit -m "Log webhook timestamp"
          git push


