name: Log Webhook Timestamp
on:
  workflow_dispatch:
  repository_dispatch:
    types: [webhook-received]

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Git with PAT
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url origin https://dl-marketing:${{ secrets.HUBSPOT_PAT }}@github.com/dl-marketing/hubspot-workflow-checker.git
      
      - name: Log Timestamp and Push
        run: |
          echo "Webhook received at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> webhook-timestamps.txt
          git add webhook-timestamps.txt
          git commit -m "Log webhook timestamp"
          git push

